# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '高德地图2019' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 高德地图2019
  pod 'AMap2DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'

  target '高德地图2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '高德地图2019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
